# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  hello-world:
    docker:
      - image: cimg/base:current
    parameters:
      msg: 
        type: string
    steps:
      - checkout
      - run:
          name: "Print vars"
          command: |
            echo Branch: << pipeline.git.branch >>
            echo Tag: << pipeline.git.tag >>
            echo Type: <<parameters.msg >>

workflows:
  pull-request:
    jobs:
      - hello-world:
          msg: "PR"
          filters:
            branches:
              only:
                - pull/\d+/head
  new-tag:
    jobs:
      - hello-world:
          msg: "TAG"
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /v.*/
