name: Validate pull request title
on:
  pull_request:
    types: [opened, edited]

jobs:
  validation-script:
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'pull_request' }}
      steps:
        - name: Print the PR title
          run: |
            set +e
            JIRA=$(printf '%q' ${{ github.event.pull_request.title }} | grep -o "GRUB-[0-9]\{4,5\}")
            if [[ $? == 1 ]]; then
              echo "::error::PR Title does not include JIRA issue number!"
              exit 1
            else
              echo "::notice::Detected JIRA issue ${JIRA}"
            fi