name: Check PR title contains Jira issue ID
on:
  - push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: gencarnacao-cw/test-action@v2
        with:
          who-to-greet: ${{ github.context }}
          github-context: ${{ github.context }}
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}