name: Check PR title contains Jira issue ID
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  bash-script:
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'pull_request' }}
      steps:
        - name: Print the PR title
          run: |
            set +e
            printf '%q' ${{ github.event.pull_request.title }} | grep -o "GRUB-[0-9]\{4,5\}"
            if [[ $? == 1 ]]; then
              echo "::error::PR Title does not include JIRA issue number!"
              exit 1
            fi