name: Check PR title contains Jira issue ID
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: gencarnacao-cw/test-action@v6
        with:
          context: ${{ toJSON(github) }}
