name: Check PR title contains Jira issue ID
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  bash-script:
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'pull_request' }}
      steps:
        - name: Print the PR title
          run: |
            # echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d{4,5}" || echo "::error::PR Title does not include JIRA issue number!" && exit 1
            bash --version
            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-" || echo ""
            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d*" || echo ""
            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d{4,5}" || echo ""
            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d\{4,5\}" || echo ""
            echo "${{ github.event.pull_request.title }}" | grep "GRUB-" || echo ""
            echo "${{ github.event.pull_request.title }}" | grep "GRUB-\d*" || echo ""
            echo "${{ github.event.pull_request.title }}" | grep "GRUB-\d{4,5}" || echo ""
            echo "${{ github.event.pull_request.title }}" | grep "GRUB-\d\{4,5\}" || echo ""



